"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "eluzix"
email = "eluzix@gmail.com"

[ui]
default-command = "log"
pager = "cat"
editor = "nvim"
color = "always"
#diff-editor = ["nvim", "-c", "DiffEditor ($left, $right, $output)"]

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'

[signing]
behavior = "own"
backend = "gpg"
key = "452ECCA0A809FBEC"
