"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "log"
pager = "cat"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[user]
name = "eluzix"
email = "eluzix@gmail.com"

